### ISSUE TITLE
Regression: Default diff state mode not respected.

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/diff#16]
## Testing Diff 7.x-3.3 in a D7.82 sandbox

1. When I compared revisions, I got the "HTML" (`raw`) mode shown out of the box:
   ![image](https://user-images.githubusercontent.com/2423362/135305137-170eeced-2851-418a-95b2-e9d4fbba70fb.png)
   The path I was at was `node/1/revisions/view/1/2`.
1. I switched to "Marked down" mode, which took me to `node/1/revisions/view/1/2/raw-plain`
1. I switched back to "Standard" mode, which took me to `node/1/revisions/view/1/2` (notice: no `/raw` added to the end of the path)
1. I then navigated to `admin/config/content/diff/entities` and switched the "Diff default state" setting to "- None -" (which I find of no use at all by the way), and saved settings.
1. When I compared revisions again, I got this:
   ![image](https://user-images.githubusercontent.com/2423362/135307303-770882d4-a8d5-4802-9398-81b4521fa181.png)

---

## Testing Diff 3.4.0 in a Backdrop 1.20.0 demo sandbox

1. I navigated to `admin/config/content/diff/entities` and confirmed that the "Diff default state" setting was set to "HTML view" (`raw`) out of the box.
1. When I compared revisions, I got this (which is basically the "- None -" diff mode 👎🏼 ):
   ![image](https://user-images.githubusercontent.com/2423362/135305913-84ae69c1-dec8-4098-94a3-f62b365297f3.png)
   The path I was at was `node/1/revisions/view/1/2`.
1. I switched to "Marked down" mode, which took me to `node/1/revisions/view/1/2/raw-plain` 👍🏼 
1. I switched back to "Standard" mode, which took me to `node/1/revisions/view/1/2/raw` (differs compared to the 7.x behavior, which is that no `/raw` is being added to the end of the path)
1. I navigated to `admin/config/content/diff/entities` and changed the "Diff default state" setting to "Plain view" (`raw-plain`).
1. When I compared revisions, I got the "- None -" diff mode again 👎🏼

**Comment by quicksketch** [comment]
This project doesn't have the same labels as core, but this should/could be marked RTBC. I reviewed and tested and I'm using this PR on my projects successfully. :+1:

**Comment by izmeez** [comment]
I'm wondering if this issue has been lost. Last note by @quicksketch suggests the PR #21 could be RTBC and looking at the diff the significant fix seems to be these lines:
<pre>-  $default_state = config_get('diff.settings','diff_default_state_node');
+  $default_state = config_get('diff.settings', 'diff_default_state.node');
</pre>

**Comment by quicksketch** [comment]
Yep, the PR at https://github.com/backdrop-contrib/diff/pull/21 has been on our production site for years now.

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop-contrib/diff/pull/21. Thank you @klonos!
