### ISSUE TITLE
"Use administration theme" setting is broken

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/diff#17]
Steps to reproduce:

1. In a vanilla backdrop installation, install and enable the Diff module.
1. Go to `admin/config/content/diff/entities` and make sure that the "Use administration theme" setting is on.
1. Compare two revisions of a node -> the Basis theme is being used instead of Seven 👎🏼 
1. Go to `admin/config/content/diff/entities` and disable the "Use administration theme" setting. Save.
1. Compare two revisions of a node -> the Basis theme is being used 🤷🏼

**Comment by quicksketch** [comment]
I merged https://github.com/backdrop-contrib/diff/pull/19 to resolve this issue. Thank you @klonos!
