### ISSUE TITLE
Offering to co-maintain the Diff module

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/diff#18]
Hey @Graham-72 👋🏼 not sure if you are around, but there are a few issues with this module that I would like to help fix, and I'm generally interested in helping you maintain the module. Do you accept?

**Comment by herbdool** [comment]
We could probably consider this unmaintained now.

**Comment by quicksketch** [comment]
I filed a contrib-ops request at https://github.com/backdrop-ops/contrib/issues/680 to get @klonos added (if you're still interested).
