### ISSUE TITLE
It always shows 'No visible changes'

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/diff#24]
Tested on text and integer types fields, unfortunately whatever change I make it always shows 'No visible changes'. Tried both dev and the officially released versions. Am I doing something wrong? Anyone using this module successfully?

**Comment by quicksketch** [comment]
I was seeing this problem as well. It seems to be fixed by the pull request linked in https://github.com/backdrop-contrib/diff/issues/16.

**Comment by alanmels** [comment]
Thanks for the update, works now.
