### ISSUE TITLE
Deprecated function: The each() function is deprecated. 

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/diff#26]
When viewing a diff in Standard mode, I get the following error message:

```
Deprecated function: The each() function is deprecated. This message will be suppressed on further calls in _DiffEngine->_diag() (line 315 of /var/www/html/web/modules/contrib/diff/DiffEngine.php). 
```

![image](https://user-images.githubusercontent.com/100206/199360547-765167bf-cfb5-42bc-91a3-c79fec90bad7.png)

I'm running PHP 7.4, and it looks like this function was removed entirely in PHP 8.0 (meaning Diff probably doesn't work in PHP 8)

See https://www.php.net/manual/en/function.each.php

**Comment by izmeez** [comment]
@quicksketch That is correct. Testing Diff with php 8.1.x the Diff -> Standard view returns a fatal error with ```Error: Call to undefined function each() in _DiffEngine->_diag() (line 315 of /modules/diff/DiffEngine.php)``` and no display. Meanwhile with php 7.4.x it works with deprecated warning.

**Comment by izmeez** [comment]
Reminded of this on php 7.4 again while on page `/admin/config/development/configuration` Synchronize. Selected files copied from `staging` to `active` and page refreshed with `Empty caches`.

> Deprecated function: The each() function is deprecated. This message will be suppressed on further calls in _DiffEngine->_diag() line 315 of /modules/diff/DiffEngine.php

**Comment by quicksketch** [comment]
This has been fixed as a side-effect of switching to the core DiffEngine in https://github.com/backdrop-contrib/diff/issues/27.
