### ISSUE TITLE
Switch to using the Core-provided Diff Engine

### ISSUE THREAD

**Issue by quicksketch** [backdrop-contrib/diff#27]
Backdrop core includes a diff engine that is more up-to-date and compatible with PHP 8+, which would avoid problems like https://github.com/backdrop-contrib/diff/issues/26. Right now Diff module duplicates the entire DiffEngine which is directly available in core (used by the config sync form). This module should stop shipping it's own copy and use the one in core instead.

**Comment by laryn** [comment]
Related, perhaps: I had this module enabled on a site and found I couldn't see config diffs in the synchronize screen, due to this error:

> TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "diff_node_revision_access" not found or invalid function name in _menu_check_access() (line 700 of /path/core/includes/menu.inc).

**Comment by quicksketch** [comment]
This was fixed by https://github.com/backdrop-contrib/diff/pull/34 (thanks @anemirovsky!)
