### ISSUE TITLE
Deprecated function element_sort()

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/diff#28]
Similarly to https://github.com/backdrop-contrib/diff/issues/26 it's giving:

```
The function diff_compare_entities() (diff.pages.inc:480) called deprecated function element_sort(). It will be removed in the next major release of Backdrop.
```

Replacing _element_sort()_ with [backdrop_sort()](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_sort/1) didn't work. So until https://github.com/backdrop-contrib/diff/issues/27 is resolved, I need Comment Alter module (which depends on Diff) to work properly without flooding the log with the above error and therefore came up with a temporary solution in the PR offered below.

**Comment by quicksketch** [comment]
> Replacing element_sort() with [backdrop_sort()](https://docs.backdropcms.org/api/backdrop/core%21includes%21common.inc/function/backdrop_sort/1) didn't work.

Hm, why not? `backdrop_sort()` replaced `element_sort()` everywhere else in core, so it should be able to replace any previous usage. I'll see if I can use it rather than re-introducing an internal replacement for `element_sort()`.

**Comment by quicksketch** [comment]
`backdrop_sort()` seemed to work fine. I merged committed a fix in https://github.com/backdrop-contrib/diff/commit/af67e5c64639e121419693450fbc25ef2ac6d611. Thanks for the report! I just got added as a maintainer here so if there are further issues please reopen if needed.
