### ISSUE TITLE
Release 1.x-3.2.0 is not working.

### ISSUE THREAD

**Issue by Graham-72** [backdrop-contrib/diff#3]
Apologies for releasing this prematurely. Something has gone wrong and requires more work.

**Comment by Graham-72** [comment]
@klonos I have got into difficulties with trying to get this repository to be a working version of diff and I would like to delete this repository and re-work the porting from the D7 release. But because I have moved this into backdrop-contrib I cannot delete it and start again. Please can you delete it for me?

**Comment by klonos** [comment]
Not sure if I have permissions to do so. Checking...

But deleting the repo, I think will also delete the issues. Not sure if you'd want that. Also not sure what will happen on the b.org side that pulls the releases from GitHub (for use with the project browser too).

**Comment by klonos** [comment]
Seems like I do have permission to delete repos. Not sure if I should though. Can you please hold off until we get some feedback here from @quicksketch?

**Comment by Graham-72** [comment]
Well I now have a local version that works at least partially but because of something I have done wrong I seem unable to push updates from my copy in PhpStorm to this repo in backdrop-contrib. So I am hoping to start afresh with a new repo at Graham-72/diff, and make sure that is OK before transferring to backdrop-contrib.

**Comment by klonos** [comment]
👍 @Graham-72 ...sounds like a plan. Sorry, but I need to wait confirmation/approval from a more experienced person such as @quicksketch before doing such a destructive thing as deleting a repo. I hope you understand.

**Comment by Graham-72** [comment]
The Drupal recommended release is tagged 7.x-3.2, dated 2012-Nov-13, but the 7.x-3.x repository includes several more recent commits. In order to achieve functional parity with the Drupal release 7.x-3.2 I am going to try a PR that reworks some of this initial port, removing the more recent commits.

**Comment by Graham-72** [comment]
For information, this release 1.x-3.2.0 is partially working and I am now working on achieving parity with the current Drupal 7 release 7.x-3.4 including updates for conversion from existing D7 sites. I will then release a Backdrop version 1.x-3.4.0.
