### ISSUE TITLE
Diff php 8.1.x deprecated warnings

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/diff#31]
With php 8.1.10 and the diff module I am seeing the following:
<pre>    Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in diff_diffs_show() (line 176 of \modules\diff\diff.pages.inc).
    Deprecated function: explode(): Passing null to parameter #2 ($string) of type string is deprecated in diff_get_rows() (line 501 of \modules\diff\diff.module).
    Deprecated function: explode(): Passing null to parameter #2 ($string) of type string is deprecated in diff_get_rows() (line 502 of \modules\diff\diff.module).</pre>

This may be similar to https://github.com/backdrop-contrib/diff/issues/8

**Comment by izmeez** [comment]
These warnings appear when user goes to Revisions tab menu and click on "Compare".

**Comment by quicksketch** [comment]
Thanks @izmeez. I've addressed this issue in https://github.com/backdrop-contrib/diff/commit/af67e5c64639e121419693450fbc25ef2ac6d611.
