### ISSUE TITLE
Passing null to parameter - str_replace(), explode()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/diff#32]
I get these errors when viewing a diff, under PHP 8.1:

Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in diff_diffs_show() (line 176 of /app/httpdocs/modules/diff/diff.pages.inc).
Deprecated function: explode(): Passing null to parameter #2 ($string) of type string is deprecated in diff_get_rows() (line 501 of /app/httpdocs/modules/diff/diff.module).
Deprecated function: explode(): Passing null to parameter #2 ($string) of type string is deprecated in diff_get_rows() (line 502 of /app/httpdocs/modules/diff/diff.module).

**Comment by quicksketch** [comment]
I've addressed this issue in https://github.com/backdrop-contrib/diff/commit/af67e5c64639e121419693450fbc25ef2ac6d611. Thanks!
